version: "3.9"
services:
  edge:
    build:
      context: .
      dockerfile: docker/jetson.Dockerfile
    container_name: edge
    network_mode: host
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /opt/app/models:/opt/app/models
      - /opt/app/conf:/opt/app/conf
      - /opt/app/data:/opt/app/data
      - /var/log/app:/var/log/app
    command: ["python", "service_p9.py", "api", "--port", "8080", "--onnx", "/opt/app/models/current.onnx", "--conf", "/opt/app/conf/runtime.yaml"]

