services:
  p1_ingest:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    environment:
      - TF=${TF:-5m}
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python ingest_cg_5m.py --symbol \"$$sym\" --tf ${TF:-5m} --days ${DAYS:-90} --slice-days 7 --out data/parquet/${TF:-5m}/$$sym"]

  p2_features:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python features_p2.py build --glob \"data/parquet/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out \"data/features/${TF:-5m}/$$sym\" --warmup 8640 --winsor_low 0.01 --winsor_high 0.99"]

  p3_label:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python label_p3.py triple-barrier --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --raw \"data/parquet/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out \"data/labels/${TF:-5m}/$$sym\" --tf ${TF:-5m} --k 1.2 --H ${H:-36} --atr_window 14"]

  p4_sampling:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p4.py iforest-train --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out data/masks/${TF:-5m}/$$sym/ifgate.parquet --q 0.995 --rolling-days 30 --seed 42 --folds 5 && python cli_p4.py smote-windows --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --mask data/masks/${TF:-5m}/$$sym/ifgate.parquet --W ${WINDOW:-144} --out data/aug/train_smote/$$sym --seed 42 --folds 5 && python cli_p4.py report-classmix --pre data/train/$$sym --post data/aug/train_smote/$$sym --out reports/p4_classmix_$$sym.json"]

  p5_train:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py train --model gru --window ${WINDOW:-144} --cv walkforward --embargo 1D --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out models/gru_${TF:-5m}/$$sym --seed 42 --folds 5 --folds-out artifacts/folds_$$sym.json --smote-dir data/aug/train_smote/$$sym"]

  p5_train_gpu:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    gpus: all
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - NVIDIA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py train --model gru --window ${WINDOW:-144} --cv walkforward --embargo 1D --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out models/gru_${TF:-5m}/$$sym --seed 42 --folds 5 --folds-out artifacts/folds_$$sym.json --smote-dir data/aug/train_smote/$$sym"]

  p5_train_gpu_jetson:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py train --model gru --window ${WINDOW:-144} --cv walkforward --embargo 1D --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --out models/gru_${TF:-5m}/$$sym --seed 42 --folds 5 --folds-out artifacts/folds_$$sym.json --smote-dir data/aug/train_smote/$$sym"]

  p6_calibrate:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py calibrate --probs artifacts/p5_oos_probs/$$sym --method temperature --out models/calib_$$sym.json --verbose"]

  p6_ensemble:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py ensemble --calib models/calib_$$sym.json --probs artifacts/p5_oos_probs/$$sym --weight-by EV --out models/ensemble_5m_$$sym.json --cost_bps 5 --verbose"]

  p6_thresholds:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python cli_p5.py tune-threshold --ensemble models/ensemble_5m_$$sym.json --probs artifacts/p5_oos_probs/$$sym --grid 0.50:0.80:0.025 --cost bps:5 --out reports/p6_oos_summary_$$sym.json --verbose"]

  p5_oos_export:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python p5_export_oos.py run --features \"data/features/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --labels \"data/labels/${TF:-5m}/$$sym/y=*/m=*/d=*/part-*.parquet\" --models-root models/gru_${TF:-5m}/$$sym --out artifacts/p5_oos_probs/$$sym --embargo 1D --folds 5 --window ${WINDOW:-144} --folds-json artifacts/folds_$$sym.json"]

  p8_export:
    profiles: ["train"]
    image: crypto_nn_train
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./artifacts:/workspace/artifacts
      - ./models:/workspace/models
      - ./reports:/workspace/reports
    env_file:
      - secrets/.env
    command: ["bash","-lc","sym=$(echo ${SYMS:-BTCUSDT} | cut -d',' -f1); python -m app.export.cli_p8_export onnx --ckpt models/gru_${TF:-5m}/$$sym/*/best.pt --fp16 --out export/model_${TF:-5m}_$$sym_fp16.onnx --preproc conf/preproc_5m.yaml --ensemble models/ensemble_5m_$$sym.json --window ${WINDOW:-144} --sample 2048"]
