x-app: &app
  build: .
  working_dir: /app
  env_file:
    - secrets/.env
  environment:
    - PYTHONUNBUFFERED=1
  volumes:
    - ./:/app
    - ./data:/app/data
    - ./reports:/app/reports

services:
  # P1 – 5m default
  ingest_5m:
    <<: *app
    command: [
      "python", "ingest_cg_5m.py",
      "--symbol", "BTCUSDT",
      "--tf", "5m",
      "--days", "80",
      "--out", "data/parquet/5m/BTCUSDT"
    ]
  qa_5m:
    <<: *app
    command: [
      "python", "qa_p1_5m.py",
      "--glob", "data/parquet/5m/BTCUSDT/y=*/m=*/d=*/part-*.parquet",
      "--out", "reports/p1_qa_core_5m_80d.json",
      "--days", "80"
    ]
  duckdb_view_5m:
    <<: *app
    command: [
      "python", "duckview.py", "create",
      "--db", "meta/duckdb/p1.duckdb",
      "--glob", "data/parquet/5m/BTCUSDT/y=*/m=*/d=*/part-*.parquet",
      "--view", "bars_5m"
    ]

  ingest:
    <<: *app
    command: [
      "python", "ingest_cg.py", "ingest", "coinglass",
      "--conf", "conf/p1_inputs_cg.yaml"
    ]
  ingest_debug:
    <<: *app
    environment:
      - DEBUG=1
    command: [
      "python", "ingest_cg.py", "ingest", "coinglass",
      "--conf", "conf/p1_inputs_cg.yaml", "--debug"
    ]

  qa:
    <<: *app
    command: [
      "python", "qa_p1.py", "qa",
      "--glob", "data/parquet/15m/BTCUSDT/**/*.parquet",
      "--out", "reports/p1_qa_core.json",
      "--conf", "conf/p1_inputs_cg.yaml"
    ]

  duckdb_view:
    <<: *app
    command: [
      "python", "qa_p1.py", "duckdb-view",
      "--glob", "data/parquet/15m/BTCUSDT/**/*.parquet",
      "--view", "bars_15m",
      "--db", "meta/duckdb/p1.duckdb"
    ]

  # P2 – 5m feature builder
  features_build:
    <<: *app
    command: [
      "python", "features_p2.py", "build",
      "--glob", "data/parquet/5m/BTCUSDT/y=*/m=*/d=*/part-*.parquet",
      "--out", "data/features/5m/BTCUSDT",
      "--warmup", "8640", "--winsor_low", "0.01", "--winsor_high", "0.99"
    ]
  features_validate:
    <<: *app
    command: [
      "python", "features_p2.py", "validate",
      "--glob", "data/features/5m/BTCUSDT/**/*.parquet",
      "--qa", "reports/p2_qa_5m_80d.json",
      "--schema", "reports/p2_feature_schema.json",
      "--horizon_days", "80",
      "--warmup", "8640"
    ]
  features_bench:
    <<: *app
    command: [
      "python", "features_p2.py", "bench",
      "--glob", "data/features/5m/BTCUSDT/**/*.parquet",
      "--report", "reports/p2_bench_5m_80d.csv"
    ]
  duck_view_feat:
    <<: *app
    command: [
      "python", "duck_view.py", "create-view",
      "--glob", "data/features/5m/BTCUSDT/y=*/m=*/d=*/part-*.parquet",
      "--view", "feat_5m",
      "--db", "meta/duckdb/p1.duckdb"
    ]

  # P6 – Calibration, Ensemble, Threshold Tuning
  p6_calibrate:
    <<: *app
    command: [
      "python", "cli_p5.py", "calibrate",
      "--probs", "artifacts/p5_oos_probs/*.parquet",
      "--method", "temperature",
      "--out", "models/calib.json"
    ]
  p6_ensemble:
    <<: *app
    command: [
      "python", "cli_p5.py", "ensemble",
      "--calib", "models/calib.json",
      "--probs", "artifacts/p5_oos_probs/*.parquet",
      "--weight-by", "EV",
      "--out", "models/ensemble_5m.json",
      "--cost_bps", "5"
    ]
  p6_tune_threshold:
    <<: *app
    command: [
      "python", "cli_p5.py", "tune-threshold",
      "--ensemble", "models/ensemble_5m.json",
      "--probs", "artifacts/p5_oos_probs/*.parquet",
      "--grid", "0.50:0.80:0.025",
      "--cost", "bps:5",
      "--out", "reports/p6_oos_summary.json"
    ]
